### PR TITLE
Use google maps dir

### PR DESCRIPTION
**Pull request by andrii-suse**
Link "Map showing the closest mirrors" will lead to url in form like:
http://maps.google.com/maps/dir//37.750999,-97.821999/49.417000,8.700000/34.771999,113.726997/37.750999,-97.821999

### CODE REVIEW

**Comment by lrupp** [comment]
Not a 100% replacement, but better than the current state. Thanks!

**Comment by darix** [comment]
does openstreetmap have something we can use?

**Comment by bmwiedemann** [comment]
Something like https://www.openstreetmap.org/#map=7/50.625/6.339

**Comment by andrii-suse** [comment]
I did spend like an hour trying to google working examples where several points can be specified in url the same way as google api did before requiring token with linked credit card. 
Maybe somebody can point to working solution instead of raw ideas?

**Pull request merged**
