### PR TITLE
Use lobject for zsums

### LINKED ISSUE #22: mb makehashes crash (because of zsync feature?)
From https://github.com/poeml/mirrorbrain/issues/176

Activating zsync in the Mirrorbrain configuration and run the following to get the zsync "file" done:
`mb makehashes /var/www/download.kiwix.org/ -v --force -t /usr/share/mirrorbrain`
crashes.

Moving the chunk size to 4MB works partly, but mb makehashes still crashes with a file of 200GB.

### PR DESCRIPTION
**Pull request by andrii-suse**
Previous implementation did try to insert zsums using hex representation, which did
result for huge files in memory allocation bigger than 1G and led to memory errors.

Fixes https://github.com/openSUSE/mirrorbrain/issues/22

### CODE REVIEW

**Comment by andrii-suse** [comment]
some benchmarks in local environs environment:
a) BIG_FILE_SIZE=100G REBUILD=1 bash -x mirrorbrain/t/docker/environs/07-zsync.sh
b) BIG_FILE_SIZE=200G REBUILD=1 bash -x mirrorbrain/t/docker/environs/07-zsync.sh
```
Case   |  With fix   |  RAM usage  |  CPU Time |  Success
-------------------------------------------------------------------------------
a)     |    No       |   5.177g    |    19:30  |    yes
a)     |    Yes      |   2.949g    |    18:23  |    yes
b)     |    No       |   9.351g    |    35:41  |    crash
b)     |    Yes      |   5.864g    |    35:33  |    yes

**Comment by darix** [comment]
is "crash" in this case just "killed for OOM"?

**Comment by andrii-suse** [comment]
> is "crash" in this case just "killed for OOM"?

Not exactly. According to my research - Postgres will not allocate chunks bigger than 1G, even if RAM is available.

**Comment by darix** [comment]
I care more about the zsync side later, when people download from us via zsync.

**Pull request merged**
